services:
  bati-cuisine-app:
    build: .
    container_name: bati-cuisine-app
    depends_on:
      - postgres-db
    environment:
      - DB_URL=jdbc:postgresql://postgres-db:5432/baticuisine
      - DB_USER=postgres
      - DB_PASSWORD=password
    networks:
      - bati-cuisine-network

  postgres-db:
    image: postgres:15
    container_name: bati-cuisine-postgres
    environment:
      POSTGRES_DB: baticuisine  # This ensures the correct database is created
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - bati-cuisine-network
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistent storage

networks:
  bati-cuisine-network:
    driver: bridge

volumes:
  postgres-data:
